# permissions for end users to view secretmirrors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretmirror-viewer-role
rules:
- apiGroups:
  - secret.nakamasato.com
  resources:
  - secretmirrors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secret.nakamasato.com
  resources:
  - secretmirrors/status
  verbs:
  - get
